# Generated by Django 2.0.5 on 2018-05-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artile',
            new_name='Article',
        ),
    ]
